mknix
typedef double mknix::data_type
double mknix::interpolate1D(double key, const std::map< double, double > &theMap)
Referenced by mknix::LoadThermalBody::getLoadThermalBody, mknix::LoadThermalBoundary1D::getLoadThermalBoundary1D, mknix::Material::getCapacity, mknix::Material::getKappa, mknix::Motion::update, mknix::SystemChain::update.
std::unique_ptr<T> mknix::make_unique(Args &&...args)
Stand-in for std::make_unique included in C++14
static lmx::Vector<double> mknix::gravity(3)
void mknix::setSignal(std::string node, std::vector< double >)
std::vector<double> mknix::getSignal(std::string node)