mknix::Analysis
Simulation* mknix::Analysis::theSimulation
Referenced by mknix::AnalysisDynamic::AnalysisDynamic, mknix::AnalysisDynamic::solve, mknix::AnalysisStatic::AnalysisStatic, mknix::AnalysisThermalDynamic::AnalysisThermalDynamic, mknix::AnalysisThermalStatic::AnalysisThermalStatic.
double mknix::Analysis::epsilon
Referenced by setEpsilon, mknix::AnalysisDynamic::AnalysisDynamic, mknix::AnalysisThermalDynamic::AnalysisThermalDynamic.
mknix::Analysis::Analysis()
mknix::Analysis::Analysis(Simulation *)
mknix::Analysis::~Analysis()
virtual std::string mknix::Analysis::type()=0
Referenced by mknix::Simulation::runThermalAnalysis, mknix::Simulation::runMechanicalAnalysis.
void mknix::Analysis::setEpsilon(double epsilon_in)
References epsilon.
Referenced by mknix::Simulation::runMechanicalAnalysis.
virtual void mknix::Analysis::solve(lmx::Vector< data_type > *, lmx::Vector< data_type > *=0, lmx::Vector< data_type > *=0)=0
Referenced by mknix::Simulation::runThermalAnalysis, mknix::Simulation::runMechanicalAnalysis.
virtual void mknix::Analysis::init(lmx::Vector< data_type > *)
virtual void mknix::Analysis::nextStep()
Referenced by mknix::Simulation::solveStep.