mknix::Body
std::string mknix::Body::title
Referenced by outputToFile, mknix::FlexBody::outputToFile, mknix::FlexBody::writeBodyInfo, mknix::RigidBody::outputToFile, mknix::RigidBody::writeBodyInfo.
Node* mknix::Body::lastNode
Referenced by initialize, getLastNode.
std::vector<Node *> mknix::Body::nodes
Referenced by initialize, setTemperature, outputStep, translate, addNode, getNodesSize, getNodes, getNode, addNodeToBoundaryGroup, mknix::FlexBody::initialize, mknix::FlexBody::addPoint, mknix::FlexBody::getNode, mknix::FlexFrameGalerkin::outputStep, mknix::FlexGlobalGalerkin::outputStep, mknix::RigidBody::getNode, mknix::RigidBody::outputStep, mknix::RigidBody::outputToFile, mknix::RigidBar::addNode, mknix::RigidBody2D::addNode, mknix::RigidBody3D::addNode.
std::vector<Node *> mknix::Body::bondedBodyNodes
Referenced by initialize, addNodes.
std::map<std::string, BoundaryGroup *> mknix::Body::boundaryGroups
Referenced by ~Body, initialize, calcExternalHeat, assembleExternalHeat, addBoundaryGroup, addNodeToBoundaryGroup, addCellToBoundaryGroup, setLoadThermalInBoundaryGroup.
std::vector<std::vector<int> > mknix::Body::boundaryConnectivity
Referenced by outputToFile, addBoundaryConnectivity.
std::map<Point *, Point *> mknix::Body::linearBoundary
Map of linear boundary.
Referenced by addBoundaryLine, getBoundarySize, getBoundaryFirstNode, getBoundaryNextNode, mknix::FlexBody::writeBodyInfo, mknix::FlexBody::writeBoundaryNodes, mknix::FlexBody::writeBoundaryConnectivity.
std::map<int, Cell *> mknix::Body::cells
Map of integration cells.
Referenced by ~Body, initialize, calcCapacityMatrix, calcConductivityMatrix, calcExternalHeat, assembleCapacityMatrix, assembleConductivityMatrix, assembleExternalHeat, getCellLastNumber, addCell, mknix::FlexBody::writeBodyInfo, mknix::FlexFrameGalerkin::calcMassMatrix, mknix::FlexFrameGalerkin::calcInternalForces, mknix::FlexFrameGalerkin::calcExternalForces, mknix::FlexFrameGalerkin::calcTangentMatrix, mknix::FlexFrameGalerkin::assembleTangentMatrix, mknix::FlexFrameGalerkin::outputStep, mknix::FlexGlobalGalerkin::calcMassMatrix, mknix::FlexGlobalGalerkin::calcInternalForces, mknix::FlexGlobalGalerkin::calcExternalForces, mknix::FlexGlobalGalerkin::calcTangentMatrix, mknix::FlexGlobalGalerkin::assembleTangentMatrix, mknix::FlexGlobalGalerkin::outputStep.
bool mknix::Body::computeEnergy
Referenced by outputStep.
bool mknix::Body::isThermal
Referenced by outputStep, setMechanical.
std::vector<lmx::Vector<data_type> *> mknix::Body::temperature
Referenced by ~Body, outputStep, outputToFile.
LoadThermalBody* mknix::Body::loadThermalBody
Referenced by calcExternalHeat, setLoadThermal.
mknix::Body::Body()
mknix::Body::Body(std::string)
Constructor with 1 parameter.
title_in Name of body in the system. Will be the same as the associated material body
mknix::Body::~Body()
References temperature, cells, boundaryGroups.
virtual std::string mknix::Body::getType()=0
Referenced by mknix::RigidBody::writeBodyInfo.
void mknix::Body::initialize()
Cascade initialization funtion. Calls the initialize methods for each of the Cells and tells them to compute their shapefunction values. Both loops are parallelized.
void
References lastNode, nodes, cells, bondedBodyNodes, boundaryGroups.
Referenced by mknix::FlexBody::initialize.
void mknix::Body::calcCapacityMatrix()
Computes the local Capacity of the material body by calling each cell's cascade function.
void
References cells.
void mknix::Body::calcConductivityMatrix()
Computes the local Conductivity of the material body by calling each cell's cascade function.
void
References cells.
void mknix::Body::calcExternalHeat()
Computes the local volumetric heat vector of the material body by calling each cell's cascade function.
void
References cells, loadThermalBody, boundaryGroups.
void mknix::Body::assembleCapacityMatrix(lmx::Matrix< data_type > &)
Assembles the local conductivity into the global matrix by calling each cell's cascade function.
globalCapacity Reference to the global matrix of the thermal simulation. void
References cells.
void mknix::Body::assembleConductivityMatrix(lmx::Matrix< data_type > &)
Assembles the local conductivity into the global matrix by calling each cell's cascade function.
globalConductivity Reference to the global matrix of the thermal simulation. void
References cells.
void mknix::Body::assembleExternalHeat(lmx::Vector< data_type > &)
Assembles the local volumetric heat into the global heat load vector by calling each cell's cascade function.
void
References cells, boundaryGroups.
virtual void mknix::Body::calcMassMatrix()=0
virtual void mknix::Body::calcExternalForces()=0
virtual void mknix::Body::assembleMassMatrix(lmx::Matrix< data_type > &)=0
virtual void mknix::Body::assembleExternalForces(lmx::Vector< data_type > &)=0
void mknix::Body::setTemperature(double)
References nodes.
virtual void mknix::Body::setMechanical()
References isThermal.
virtual void mknix::Body::setOutput(std::string)=0
virtual void mknix::Body::outputStep(const lmx::Vector< data_type > &, const lmx::Vector< data_type > &)=0
virtual void mknix::Body::outputStep(const lmx::Vector< data_type > &)=0
void mknix::Body::outputStep()
Postprocess and store thermal step results for any analysis.
void
References isThermal, nodes, temperature, computeEnergy.
Referenced by mknix::FlexFrameGalerkin::outputStep, mknix::FlexGlobalGalerkin::outputStep, mknix::RigidBody::outputStep.
void mknix::Body::outputToFile(std::ofstream *)
Streams the data stored during the analysis to a file.
outFile Output files void
References boundaryConnectivity, title, temperature.
Referenced by mknix::FlexBody::outputToFile, mknix::RigidBody::outputToFile.
virtual void mknix::Body::addNode(Node *node_in)
References nodes.
Referenced by mknix::RigidBar::addNode, mknix::RigidBody2D::addNode, mknix::RigidBody3D::addNode.
void mknix::Body::addNodes(std::vector< Node * > &nodes_in)
References bondedBodyNodes.
virtual int mknix::Body::getNodesSize()
References nodes.
std::vector<Node *>& mknix::Body::getNodes()
References nodes.
virtual Node* mknix::Body::getNode(int node_number)
References nodes.
virtual Node* mknix::Body::getLastNode()
References lastNode.
Referenced by mknix::FlexBody::writeBodyInfo.
virtual void mknix::Body::addBoundaryLine(Point *node1, Point *node2)
References linearBoundary.
void mknix::Body::addBoundaryConnectivity(std::vector< int > connectivity_in)
References boundaryConnectivity.
virtual int mknix::Body::getBoundarySize()
References linearBoundary.
Referenced by mknix::FlexBody::writeBodyInfo.
virtual Point* mknix::Body::getBoundaryFirstNode()
References linearBoundary.
Referenced by mknix::FlexBody::writeBodyInfo.
virtual Point* mknix::Body::getBoundaryNextNode(Point *node_in)
References linearBoundary.
void mknix::Body::addBoundaryGroup(std::string boundaryName_in)
References boundaryGroups.
void mknix::Body::addNodeToBoundaryGroup(int nodeNumber_in, std::string boundaryName_in)
References nodes, boundaryGroups.
void mknix::Body::addCellToBoundaryGroup(CellBoundary *cell_in, std::string boundaryName_in)
References boundaryGroups.
void mknix::Body::setLoadThermalInBoundaryGroup(LoadThermalBoundary1D *load_in, std::string boundaryName_in)
References boundaryGroups.
int mknix::Body::getCellLastNumber()
References cells.
virtual void mknix::Body::addCell(int num, Cell *cell_in)
References cells.
virtual void mknix::Body::writeBodyInfo(std::ofstream *)=0
virtual void mknix::Body::writeBoundaryNodes(std::vector< Point * > &)=0
virtual void mknix::Body::writeBoundaryConnectivity(std::vector< std::vector< Point * > > &)=0
void mknix::Body::translate(double, double, double)
References nodes.
virtual void mknix::Body::setLoadThermal(LoadThermalBody *theLoad)
References loadThermalBody.