mknix::Material
int mknix::Material::dim
Dimension of space
double mknix::Material::capacity
Thermal specific capacity
double mknix::Material::kappa
Thermal conductivity
double mknix::Material::young
Young Modulus.
double mknix::Material::poisson
Poisson Modulus.
double mknix::Material::beta
Thermal expansion
double mknix::Material::lambda
double mknix::Material::mu
Lame's coefficients.
double mknix::Material::density
Density.
std::map<double, double> mknix::Material::m_capacity
std::map<double, double> mknix::Material::m_kapppa
lmx::DenseMatrix<double> mknix::Material::D
Constitutive Linear
lmx::DenseMatrix<double> mknix::Material::C
Constitutive Saint-Venant Kirchoff
cofe::TensorRank2Sym<2,double> mknix::Material::E
cofe::TensorRank2Sym<3,double> mknix::Material::E3
mknix::Material::Material()
mknix::Material::~Material()
double mknix::Material::getE()
double mknix::Material::getMu()
double mknix::Material::getDensity()
Referenced by mknix::GaussPoint::computeCij, mknix::GaussPoint2D::computeMij, mknix::GaussPoint2D::computeStress, mknix::GaussPoint2D::computeNLStress, mknix::GaussPoint3D::computeMij, mknix::GaussPoint3D::computeNLStress.
double mknix::Material::getCapacity(double temp_in=0)
References mknix::interpolate1D.
Referenced by mknix::GaussPoint::computeCij.
double mknix::Material::getKappa(double temp_in=0)
References mknix::interpolate1D.
Referenced by mknix::GaussPoint::computeHij.
lmx::DenseMatrix<double>& mknix::Material::getD()
Referenced by mknix::GaussPoint2D::computeKij, mknix::GaussPoint2D::computeStress, mknix::GaussPoint3D::computeKij, mknix::GaussPoint3D::computeStress.
lmx::DenseMatrix<double>& mknix::Material::getC()
Referenced by mknix::GaussPoint2D::computeNLKij, mknix::GaussPoint3D::computeNLKij.
void mknix::Material::setThermalProps(double capacity_in, double kappa_in, double beta_in, double density_in)
void mknix::Material::setMechanicalProps(int dim_in, double young_in, double poisson_in, double density_in)
References computeD, computeC.
void mknix::Material::addThermalCapacity(double temp_in, double capacity_in)
void mknix::Material::addThermalConductivity(double temp_in, double conductivity_in)
void mknix::Material::computeD()
Referenced by setMechanicalProps.
void mknix::Material::computeC()
Referenced by setMechanicalProps.
double mknix::Material::getCsym(int &i, int &j, int &k, int &l)
void mknix::Material::computeS(cofe::TensorRank2Sym< 2, double > &S, const cofe::TensorRank2< 2, double > &F, double)
Referenced by mknix::GaussPoint2D::computeNLFint, mknix::GaussPoint3D::computeNLFint.
void mknix::Material::computeS(cofe::TensorRank2Sym< 3, double > &S, const cofe::TensorRank2< 3, double > &F)
double mknix::Material::computeEnergy(const cofe::TensorRank2< 2, double > &S)
Referenced by mknix::GaussPoint2D::calcElasticE, mknix::GaussPoint3D::calcElasticE.
double mknix::Material::computeEnergy(const cofe::TensorRank2< 3, double > &S)
double mknix::Material::Cijkl(int &i, int &j, int &k, int &l)