mknix::ShapeFunction
int mknix::ShapeFunction::dim
Referenced by mknix::ShapeFunctionMLS::ShapeFunctionMLS, mknix::ShapeFunctionRBF::ShapeFunctionRBF, mknix::ShapeFunctionTriangleSigned::calc.
lmx::DenseMatrix<double> mknix::ShapeFunction::phi
Referenced by outputValues, gnuplotOut, mknix::ShapeFunctionLinearX::ShapeFunctionLinearX, mknix::ShapeFunctionLinearX::calc, mknix::ShapeFunctionLinear::ShapeFunctionLinear, mknix::ShapeFunctionLinear::calc, mknix::ShapeFunctionMLS::ShapeFunctionMLS, mknix::ShapeFunctionRBF::ShapeFunctionRBF, mknix::ShapeFunctionTetrahedron::ShapeFunctionTetrahedron, mknix::ShapeFunctionTetrahedron::calc, mknix::ShapeFunctionTriangle::ShapeFunctionTriangle, mknix::ShapeFunctionTriangle::calc, mknix::ShapeFunctionTriangleSigned::ShapeFunctionTriangleSigned, mknix::ShapeFunctionTriangleSigned::calc.
Point* mknix::ShapeFunction::gp
Referenced by outputValues, gnuplotOut, mknix::ShapeFunctionLinearX::calc, mknix::ShapeFunctionLinear::calc, mknix::ShapeFunctionMLS::ShapeFunctionMLS, mknix::ShapeFunctionMLS::calc, mknix::ShapeFunctionRBF::calc, mknix::ShapeFunctionTetrahedron::calc, mknix::ShapeFunctionTetrahedron::compute_abcd, mknix::ShapeFunctionTriangle::calc, mknix::ShapeFunctionTriangleSigned::calc.
mknix::ShapeFunction::ShapeFunction()
mknix::ShapeFunction::ShapeFunction(const ShapeFunction *)
mknix::ShapeFunction::ShapeFunction(Point *)
mknix::ShapeFunction::~ShapeFunction()
virtual void mknix::ShapeFunction::calc()=0
Referenced by mknix::GaussPoint::shapeFunSolve, mknix::GaussPoint2D::fillFEmatrices, mknix::GaussPoint3D::fillFEmatrices, mknix::GaussPointBoundary::shapeFunSolve, mknix::Point::shapeFunSolve.
virtual double mknix::ShapeFunction::getPhi(int i, int j)
Referenced by mknix::GaussPoint::computeCij, mknix::GaussPoint::computeHij, mknix::GaussPoint::computeQext, mknix::GaussPoint2D::shapeFunSolve, mknix::GaussPoint2D::fillFEmatrices, mknix::GaussPoint2D::computeMij, mknix::GaussPoint2D::computeStress, mknix::GaussPoint2D::computeNLStress, mknix::GaussPoint2D::computeNLFint, mknix::GaussPoint2D::computeNLKij, mknix::GaussPoint3D::shapeFunSolve, mknix::GaussPoint3D::fillFEmatrices, mknix::GaussPoint3D::computeMij, mknix::GaussPoint3D::computeNLStress, mknix::GaussPoint3D::computeNLFint, mknix::GaussPoint3D::computeNLKij, mknix::GaussPointBoundary::computeQext, mknix::Node::getConf, mknix::Node::getTemp, mknix::Node::getShapeFunValue, mknix::Point::getTemp, mknix::Point::getConf.
virtual void mknix::ShapeFunction::setPhi(double value_in, int i, int j)
void mknix::ShapeFunction::outputValues()
References gp, mknix::Point::supportNodes, mknix::Point::X, mknix::Point::Y, phi.
void mknix::ShapeFunction::gnuplotOut()
References gp, mknix::Point::supportNodes, phi.
Referenced by mknix::Point::gnuplotOut.