mknix::FlexBody
std::string mknix::FlexBody::formulation
Referenced by setFormulation, mknix::FlexFrameGalerkin::calcInternalForces, mknix::FlexFrameGalerkin::calcTangentMatrix, mknix::FlexFrameGalerkin::outputStep, mknix::FlexGlobalGalerkin::calcInternalForces, mknix::FlexGlobalGalerkin::calcTangentMatrix, mknix::FlexGlobalGalerkin::outputStep.
std::vector<Node*> mknix::FlexBody::points
Additional points to define loads or constraints
Referenced by initialize, addPoint, getNode, getNumberOfPoints.
std::vector<Point*> mknix::FlexBody::bodyPoints
Points to define integration domain
Referenced by initialize, addBodyPoint, writeBodyInfo, getBodyPoint, getLastBodyPoint.
bool mknix::FlexBody::computeStress
Referenced by setOutput, outputToFile, mknix::FlexFrameGalerkin::outputStep, mknix::FlexGlobalGalerkin::outputStep.
bool mknix::FlexBody::computeEnergy
Referenced by setOutput, outputToFile, mknix::FlexFrameGalerkin::outputStep, mknix::FlexGlobalGalerkin::outputStep.
lmx::Matrix< data_type > mknix::FlexBody::smoothingMassMatrix
std::vector< lmx::Vector<data_type> > mknix::FlexBody::stresses
Referenced by outputToFile, mknix::FlexGlobalGalerkin::outputStep.
std::vector< lmx::Vector<data_type>* > mknix::FlexBody::energies
Referenced by outputToFile, mknix::FlexGlobalGalerkin::outputStep.
mknix::FlexBody::FlexBody()
mknix::FlexBody::FlexBody(std::string)
mknix::FlexBody::~FlexBody()
void mknix::FlexBody::initialize()
Cascade initialization funtion. Calls the initialize methods for each of the Cells and tells them to compute their shapefunction values. Both loops are parallelized.
void
References mknix::Body::initialize, points, mknix::Body::nodes, bodyPoints.
Point* mknix::FlexBody::getBodyPoint(int point_number)
References bodyPoints.
Referenced by writeBodyInfo.
virtual Node* mknix::FlexBody::getNode(int node_number)
References points, mknix::Body::nodes.
Referenced by writeBodyInfo.
Point* mknix::FlexBody::getLastBodyPoint()
References bodyPoints.
Referenced by writeBodyInfo.
virtual void mknix::FlexBody::setType(std::string type_in)=0
virtual void mknix::FlexBody::setFormulation(std::string formulation_in)
References formulation.
virtual void mknix::FlexBody::calcInternalForces()=0
virtual void mknix::FlexBody::calcTangentMatrix()=0
virtual void mknix::FlexBody::assembleInternalForces(lmx::Vector< data_type > &)=0
virtual void mknix::FlexBody::assembleTangentMatrix(lmx::Matrix< data_type > &)=0
void mknix::FlexBody::addBodyPoint(Point *, std::string)
References bodyPoints.
void mknix::FlexBody::addPoint(Node *)
References points.
void mknix::FlexBody::addPoint(int, double, double, double, double, double)
References points, mknix::Body::nodes.
virtual int mknix::FlexBody::getNumberOfPoints()
References points.
void mknix::FlexBody::setOutput(std::string)
Activates a flag for output data at the end of the analysis.
outputToFile() outputStep() outputType_in Keyword of the flag. Options are: [STRESS, ENERGY] void
References computeStress, computeEnergy.
void mknix::FlexBody::outputToFile(std::ofstream *)
Streams the data stored during the analysis to a file.
outFile Output files void
References mknix::Body::outputToFile, computeStress, mknix::Body::title, stresses, computeEnergy, energies.
void mknix::FlexBody::writeBodyInfo(std::ofstream *)
References mknix::Simulation::getDim, mknix::Body::title, bodyPoints, getNode, mknix::Point::getNumber, mknix::Body::getLastNode, getBodyPoint, getLastBodyPoint, mknix::Body::cells, mknix::Body::getBoundarySize, mknix::Body::getBoundaryFirstNode, mknix::Body::linearBoundary.
void mknix::FlexBody::writeBoundaryNodes(std::vector< Point * > &)
References mknix::Body::linearBoundary.
void mknix::FlexBody::writeBoundaryConnectivity(std::vector< std::vector< Point * > > &)
References mknix::Body::linearBoundary.