mknix::System
friend class Reader
friend class ReaderFlex
friend class ReaderRigid
friend class ReaderConstraints
friend class Contact
std::string mknix::System::title
std::map< std::string, System* > mknix::System::subSystems
std::map< std::string, RigidBody* > mknix::System::rigidBodies
std::map< std::string, FlexBody* > mknix::System::flexBodies
std::map< std::string, ThermalBody* > mknix::System::thermalBodies
std::map< std::string, Constraint* > mknix::System::constraints
std::vector< Load* > mknix::System::loads
std::map< std::string, System* >::iterator mknix::System::itSubSystems
std::map< std::string, RigidBody* >::iterator mknix::System::itRigidBodies
std::map< std::string, FlexBody* >::iterator mknix::System::itFlexBodies
std::map< std::string, ThermalBody* >::iterator mknix::System::itThermalBodies
std::map< std::string, Constraint* >::iterator mknix::System::itConstraints
std::vector< Load* >::iterator mknix::System::itLoads
mknix::System::System()
mknix::System::System(const char *)
mknix::System::~System()
std::string mknix::System::getTitle()
Referenced by mknix::ReaderConstraints::readConstraints, mknix::ReaderFlex::readFlexBodies.
void mknix::System::writeRigidBodies(std::ofstream *)
Referenced by mknix::Simulation::writeSystem.
void mknix::System::writeFlexBodies(std::ofstream *)
Referenced by mknix::Simulation::writeSystem.
void mknix::System::calcCapacityMatrix()
Referenced by mknix::Simulation::runThermalAnalysis, mknix::Simulation::dynamicThermalEvaluation.
void mknix::System::calcConductivityMatrix()
Referenced by mknix::Simulation::runThermalAnalysis, mknix::Simulation::staticThermalResidue, mknix::Simulation::dynamicThermalEvaluation.
void mknix::System::calcExternalHeat()
Referenced by mknix::Simulation::staticThermalResidue, mknix::Simulation::dynamicThermalEvaluation, mknix::Simulation::dynamicThermalResidue.
void mknix::System::assembleCapacityMatrix(lmx::Matrix< data_type > &)
Referenced by mknix::Simulation::runThermalAnalysis, mknix::Simulation::dynamicThermalEvaluation.
void mknix::System::assembleConductivityMatrix(lmx::Matrix< data_type > &)
Referenced by mknix::Simulation::runThermalAnalysis, mknix::Simulation::staticThermalResidue, mknix::Simulation::dynamicThermalEvaluation.
void mknix::System::assembleExternalHeat(lmx::Vector< data_type > &)
Referenced by mknix::Simulation::staticThermalResidue, mknix::Simulation::dynamicThermalEvaluation, mknix::Simulation::dynamicThermalResidue.
void mknix::System::calcMassMatrix()
Referenced by mknix::Simulation::runMechanicalAnalysis, mknix::Simulation::dynamicAcceleration.
void mknix::System::calcInternalForces()
Referenced by mknix::Simulation::dynamicAcceleration, mknix::Simulation::dynamicResidue, mknix::Simulation::staticResidue.
void mknix::System::calcExternalForces()
Referenced by mknix::Simulation::dynamicAcceleration, mknix::Simulation::dynamicResidue, mknix::Simulation::staticResidue.
void mknix::System::calcTangentMatrix()
Referenced by mknix::Simulation::runMechanicalAnalysis, mknix::Simulation::dynamicTangent, mknix::Simulation::staticTangent.
void mknix::System::assembleMassMatrix(lmx::Matrix< data_type > &)
Referenced by mknix::Simulation::runMechanicalAnalysis, mknix::Simulation::dynamicAcceleration.
void mknix::System::assembleInternalForces(lmx::Vector< data_type > &)
Referenced by mknix::Simulation::dynamicAcceleration, mknix::Simulation::dynamicResidue, mknix::Simulation::staticResidue.
void mknix::System::assembleExternalForces(lmx::Vector< data_type > &)
Referenced by mknix::Simulation::dynamicAcceleration, mknix::Simulation::dynamicResidue, mknix::Simulation::staticResidue.
void mknix::System::assembleTangentMatrix(lmx::Matrix< data_type > &)
Referenced by mknix::Simulation::runMechanicalAnalysis, mknix::Simulation::dynamicTangent, mknix::Simulation::staticTangent.
void mknix::System::assembleConstraintForces(lmx::Vector< data_type > &)
Referenced by mknix::Simulation::runThermalAnalysis.
void mknix::System::outputStep(const lmx::Vector< data_type > &, const lmx::Vector< data_type > &)
Referenced by mknix::Simulation::runThermalAnalysis, mknix::Simulation::runMechanicalAnalysis, mknix::Simulation::staticThermalConvergence, mknix::Simulation::dynamicThermalConvergence, mknix::Simulation::dynamicConvergence, mknix::Simulation::staticConvergence.
void mknix::System::outputStep(const lmx::Vector< data_type > &)
void mknix::System::outputToFile(std::ofstream *)
Referenced by mknix::Simulation::runThermalAnalysis, mknix::Simulation::runMechanicalAnalysis.
bool mknix::System::checkAugmented()
Referenced by mknix::Simulation::staticThermalConvergence, mknix::Simulation::dynamicThermalConvergence, mknix::Simulation::dynamicConvergence, mknix::Simulation::staticConvergence.
void mknix::System::clearAugmented()
Referenced by mknix::Simulation::staticThermalConvergence, mknix::Simulation::dynamicThermalConvergence, mknix::Simulation::dynamicConvergence, mknix::Simulation::staticConvergence.
void mknix::System::writeBoundaryNodes(std::vector< Node * > &)
Referenced by mknix::Contact::createPoints.
void mknix::System::writeBoundaryConnectivity(std::vector< std::vector< Node * > > &)
Referenced by mknix::Contact::createPolys.