mknix::Simulation
friend class Reader
friend class ReaderConstraints
friend class ReaderFlex
friend class ReaderRigid
friend class Contact
Referenced by run.
friend class SystemChain
std::string mknix::Simulation::title
std::unique_ptr<System> mknix::Simulation::baseSystem
Analysis* mknix::Simulation::theAnalysis
std::vector<std::unique_ptr<Analysis> > mknix::Simulation::analyses
std::map<int, Point *> mknix::Simulation::outputPoints
std::map<int, Node *> mknix::Simulation::nodes
std::map<int, Node *> mknix::Simulation::thermalNodes
std::map<int, Material> mknix::Simulation::materials
Map of materials.
lmx::ExactStopwatch* mknix::Simulation::globalTimer
std::ofstream* mknix::Simulation::timerFile
std::ofstream* mknix::Simulation::configurationFile
int mknix::Simulation::iterationsNLSolver
int mknix::Simulation::outputFilesDetail
double mknix::Simulation::initialTemperature
lmx::Matrix<data_type> mknix::Simulation::globalCapacity
lmx::Matrix<data_type> mknix::Simulation::globalConductivity
lmx::Vector<data_type> mknix::Simulation::globalRHSHeat
lmx::Vector<data_type> mknix::Simulation::globalExternalHeat
lmx::Vector<data_type> mknix::Simulation::globalInternalHeat
lmx::Matrix<data_type> mknix::Simulation::globalMass
lmx::Vector<data_type> mknix::Simulation::globalRHSForces
lmx::Vector<data_type> mknix::Simulation::globalInternalForces
lmx::Vector<data_type> mknix::Simulation::globalExternalForces
lmx::DenseMatrix<data_type> mknix::Simulation::globalSparsePattern
std::ofstream mknix::Simulation::outFile
double mknix::Simulation::stepTime
double mknix::Simulation::oldClockTime
lmx::Vector< double > mknix::Simulation::gravity
double mknix::Simulation::alpha
int mknix::Simulation::dimension
std::string mknix::Simulation::contact
bool mknix::Simulation::visualization
bool mknix::Simulation::outputMatrices
std::string mknix::Simulation::constraintMethod
double mknix::Simulation::epsilon
std::string mknix::Simulation::smoothingType
mknix::Simulation::Simulation()
mknix::Simulation::~Simulation()
mknix::Simulation::Simulation(const Simulation &)=delete
Simulation& mknix::Simulation::operator=(const Simulation &)=delete
void mknix::Simulation::inputFromFile(const std::string &fileIn)
std::vector< double > mknix::Simulation::getInterfaceNodesCoords()
void mknix::Simulation::setOutputFilesDetail(int level_in)
void mknix::Simulation::init()
References writeSystem.
void mknix::Simulation::setInitialTemperatures(double)
Referenced by mknix::Reader::inputFromFile.
void mknix::Simulation::solveStep()
References mknix::Analysis::nextStep.
void mknix::Simulation::solveStep(double *, double *o_output=0)
References mknix::Analysis::nextStep.
void mknix::Simulation::endSimulation()
void mknix::Simulation::run()
References Contact, writeSystem, runThermalAnalysis, runMechanicalAnalysis.
void mknix::Simulation::runThermalAnalysis(Analysis *)
References mknix::Analysis::type, mknix::Analysis::solve, getDim.
Referenced by run.
void mknix::Simulation::runMechanicalAnalysis(Analysis *)
References mknix::Analysis::type, mknix::Analysis::setEpsilon, mknix::Analysis::solve.
Referenced by run.
void mknix::Simulation::writeSystem()
Referenced by init, run.
void mknix::Simulation::staticThermalResidue(lmx::Vector< data_type > &residue, lmx::Vector< data_type > &q)
Referenced by mknix::AnalysisThermalStatic::AnalysisThermalStatic.
void mknix::Simulation::staticThermalTangent(lmx::Matrix< data_type > &tangent_in, lmx::Vector< data_type > &q)
Referenced by mknix::AnalysisThermalStatic::AnalysisThermalStatic.
bool mknix::Simulation::staticThermalConvergence(lmx::Vector< data_type > &res, lmx::Vector< data_type > &q)
References stepTriggered.
Referenced by mknix::AnalysisThermalStatic::AnalysisThermalStatic.
void mknix::Simulation::explicitThermalEvaluation(const lmx::Vector< data_type > &qt, lmx::Vector< data_type > &qtdot, double time)
Referenced by mknix::AnalysisThermalDynamic::AnalysisThermalDynamic, mknix::AnalysisThermoMechanicalDynamic::AnalysisThermoMechanicalDynamic.
void mknix::Simulation::dynamicThermalEvaluation(const lmx::Vector< data_type > &q, lmx::Vector< data_type > &qdot, double time)
Referenced by mknix::AnalysisThermalDynamic::AnalysisThermalDynamic, mknix::AnalysisThermoMechanicalDynamic::AnalysisThermoMechanicalDynamic.
void mknix::Simulation::dynamicThermalResidue(lmx::Vector< data_type > &residue, const lmx::Vector< data_type > &q, const lmx::Vector< data_type > &qdot, double time)
Referenced by mknix::AnalysisThermalDynamic::AnalysisThermalDynamic, mknix::AnalysisThermoMechanicalDynamic::AnalysisThermoMechanicalDynamic.
void mknix::Simulation::dynamicThermalTangent(lmx::Matrix< data_type > &tangent_in, const lmx::Vector< data_type > &q, double partial_qdot, double time)
Referenced by mknix::AnalysisThermalDynamic::AnalysisThermalDynamic, mknix::AnalysisThermoMechanicalDynamic::AnalysisThermoMechanicalDynamic.
bool mknix::Simulation::dynamicThermalConvergence(const lmx::Vector< data_type > &q, const lmx::Vector< data_type > &qdot, double time)
Referenced by mknix::AnalysisThermalDynamic::AnalysisThermalDynamic.
bool mknix::Simulation::dynamicThermalConvergenceInThermomechanical(const lmx::Vector< data_type > &q, const lmx::Vector< data_type > &qdot, double time)
Referenced by mknix::AnalysisThermoMechanicalDynamic::AnalysisThermoMechanicalDynamic.
void mknix::Simulation::explicitAcceleration(const lmx::Vector< data_type > &q, const lmx::Vector< data_type > &qdot, lmx::Vector< data_type > &qddot, double time)
References getDim.
Referenced by mknix::AnalysisThermoMechanicalDynamic::AnalysisThermoMechanicalDynamic.
void mknix::Simulation::dynamicAcceleration(const lmx::Vector< data_type > &q, const lmx::Vector< data_type > &qdot, lmx::Vector< data_type > &qddot, double time)
References getDim.
Referenced by mknix::AnalysisDynamic::AnalysisDynamic, mknix::AnalysisThermoMechanicalDynamic::AnalysisThermoMechanicalDynamic.
void mknix::Simulation::dynamicResidue(lmx::Vector< data_type > &residue, const lmx::Vector< data_type > &q, const lmx::Vector< data_type > &qdot, const lmx::Vector< data_type > &qddot, double time)
References getDim.
Referenced by mknix::AnalysisDynamic::AnalysisDynamic, mknix::AnalysisThermoMechanicalDynamic::AnalysisThermoMechanicalDynamic.
void mknix::Simulation::dynamicTangent(lmx::Matrix< data_type > &tangent_in, const lmx::Vector< data_type > &q, const lmx::Vector< data_type > &qdot, double partial_qdot, double partial_qddot, double time)
Referenced by mknix::AnalysisDynamic::AnalysisDynamic, mknix::AnalysisThermoMechanicalDynamic::AnalysisThermoMechanicalDynamic.
bool mknix::Simulation::dynamicConvergence(const lmx::Vector< data_type > &q, const lmx::Vector< data_type > &qdot, const lmx::Vector< data_type > &qddot, double time)
Referenced by mknix::AnalysisDynamic::AnalysisDynamic, mknix::AnalysisThermoMechanicalDynamic::AnalysisThermoMechanicalDynamic.
void mknix::Simulation::staticResidue(lmx::Vector< data_type > &residue, lmx::Vector< data_type > &q)
References getDim.
Referenced by mknix::AnalysisStatic::AnalysisStatic.
void mknix::Simulation::staticTangent(lmx::Matrix< data_type > &tangent_in, lmx::Vector< data_type > &q)
Referenced by mknix::AnalysisStatic::AnalysisStatic.
bool mknix::Simulation::staticConvergence(lmx::Vector< data_type > &res, lmx::Vector< data_type > &q)
References stepTriggered.
Referenced by mknix::AnalysisStatic::AnalysisStatic.
void mknix::Simulation::stepTriggered()
References writeConfStep.
Referenced by mknix::AnalysisDynamic::AnalysisDynamic, mknix::AnalysisThermalDynamic::AnalysisThermalDynamic, mknix::AnalysisThermoMechanicalDynamic::AnalysisThermoMechanicalDynamic, staticThermalConvergence, staticConvergence.
void mknix::Simulation::writeConfStep()
Referenced by stepTriggered.
lmx::DenseMatrix<data_type>& mknix::Simulation::getSparsePattern()
Referenced by mknix::AnalysisDynamic::solve.
static double mknix::Simulation::getGravity(int component)
Referenced by mknix::RigidBodyMassPoint::calcExternalForces, mknix::RigidBar::calcExternalForces, mknix::RigidBody2D::calcExternalForces, mknix::RigidBody3D::calcExternalForces, mknix::GaussPoint2D::computeFext, mknix::GaussPoint3D::computeFext, mknix::Reader::inputFromFile.
static double mknix::Simulation::getAlpha()
Referenced by mknix::ReaderConstraints::readConstraints, mknix::ReaderRigid::readRigidBodies.
static double mknix::Simulation::getTime()
Referenced by mknix::LoadThermalBody::getLoadThermalBody, mknix::LoadThermalBoundary1D::getLoadThermalBoundary1D.
static int mknix::Simulation::getDim()
Referenced by mknix::FlexBody::writeBodyInfo, mknix::FlexFrameGalerkin::assembleMassMatrix, mknix::FlexFrameGalerkin::outputStep, mknix::FlexGlobalGalerkin::assembleMassMatrix, mknix::FlexGlobalGalerkin::outputStep, mknix::RigidBody::assembleMassMatrix, mknix::RigidBody::assembleExternalForces, mknix::RigidBar::calcMassMatrix, mknix::RigidBar::calcExternalForces, mknix::RigidBody2D::calcMassMatrix, mknix::RigidBody2D::calcExternalForces, mknix::RigidBody3D::RigidBody3D, mknix::Constraint::assembleInternalForces, mknix::Constraint::assembleTangentMatrix, mknix::Force::Force, mknix::Load::assembleExternalForces, mknix::ReaderFlex::readFlexBodies, runThermalAnalysis, explicitAcceleration, dynamicAcceleration, dynamicResidue, staticResidue.
static std::string mknix::Simulation::getConstraintMethod()
static std::string mknix::Simulation::getSmoothingType()
Referenced by mknix::FlexFrameGalerkin::assembleMassMatrix, mknix::FlexGlobalGalerkin::assembleMassMatrix, mknix::GaussPoint2D::shapeFunSolve, mknix::GaussPoint2D::fillFEmatrices, mknix::GaussPoint2D::computeStress, mknix::GaussPoint2D::computeNLStress, mknix::GaussPoint2D::assembleRi, mknix::GaussPoint3D::shapeFunSolve, mknix::GaussPoint3D::fillFEmatrices, mknix::GaussPoint3D::computeStress, mknix::GaussPoint3D::computeNLStress.
void mknix::Simulation::storeTimeConfiguration(lmx::Vector< data_type > &q)
void mknix::Simulation::systemOuputStep(const lmx::Vector< data_type > &, const lmx::Vector< data_type > &)
void mknix::Simulation::systemOuputStep(const lmx::Vector< data_type > &)
lmx::Vector< data_type > mknix::Simulation::initThermalSimulation(Analysis *analysis, bool init=true)
lmx::Vector< data_type > mknix::Simulation::initMechanicalSimulation(Analysis *analysis, bool init=true)