mknix::Node
int mknix::Node::thermalNum
double mknix::Node::qx
double mknix::Node::qy
double mknix::Node::qz
double mknix::Node::qt
double mknix::Node::weight
mknix::Node::Node()
mknix::Node::Node(const Node &)
mknix::Node::Node(const Node *)
mknix::Node::Node(int i_in, double x_in, double y_in, double z_in)
mknix::Node::~Node()
void mknix::Node::addWeight(double w_in)
const double& mknix::Node::getWeight() const
const int& mknix::Node::getThermalNumber() const
const void mknix::Node::setNumber(int num_in)
References mknix::Point::num.
const void mknix::Node::setThermalNumber(int num_in)
const double& mknix::Node::getqt() const
Referenced by getTemp.
double mknix::Node::getqx(int i) const
Referenced by getConf.
double mknix::Node::getUx() const
References getConf, mknix::Point::X.
double mknix::Node::getUy() const
References getConf, mknix::Point::Y.
double mknix::Node::getUz() const
References getConf, mknix::Point::Z.
double mknix::Node::getU(int i) const
References getConf, mknix::Point::X, mknix::Point::Y, mknix::Point::Z.
double mknix::Node::getConf(int dof) const override
References mknix::Point::shapeFunType, mknix::Point::supportNodesSize, mknix::Point::shapeFun, mknix::ShapeFunction::getPhi, mknix::Point::supportNodes, getqx.
Referenced by getUx, getUy, getUz, getU.
double mknix::Node::getTemp() const override
References mknix::Point::shapeFunType, mknix::Point::supportNodesSize, mknix::Point::shapeFun, mknix::ShapeFunction::getPhi, mknix::Point::supportNodes, getqt.
size_t mknix::Node::getSupportSize(int deriv)
References mknix::Point::shapeFunType, mknix::Point::supportNodes.
Referenced by mknix::ConstraintDistance::ConstraintDistance, mknix::ConstraintFixedAxis::ConstraintFixedAxis, mknix::ConstraintFixedCoordinates::ConstraintFixedCoordinates, mknix::ConstraintThermalFixed::ConstraintThermalFixed.
int mknix::Node::getSupportNodeNumber(int deriv, int s_node)
References mknix::Point::shapeFunType, mknix::Point::supportNodes, mknix::Point::getNumber.
double mknix::Node::getShapeFunValue(int deriv, int s_node)
References mknix::Point::shapeFunType, mknix::Point::shapeFun, mknix::ShapeFunction::getPhi.
void mknix::Node::setUx(double ux_in)
References mknix::Point::X.
Referenced by mknix::Motion::update.
void mknix::Node::setUy(double uy_in)
References mknix::Point::Y.
Referenced by mknix::Motion::update.
void mknix::Node::setUz(double uz_in)
References mknix::Point::Z.
Referenced by mknix::Motion::update.
void mknix::Node::setqx(const lmx::Vector< data_type > &globalConf, int dim)
References mknix::Point::num.
void mknix::Node::setqt(const lmx::Vector< data_type > &globalConf)
void mknix::Node::setqt(double &temp_in)
void mknix::Node::setX(double X_in)
References mknix::Point::X.
void mknix::Node::setY(double Y_in)
References mknix::Point::Y.
void mknix::Node::setZ(double Z_in)
References mknix::Point::Z.